version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # Cập nhật ánh xạ cổng
    environment:
      ASPNETCORE_ENVIRONMENT: Development
