name: Deploy to EC2

on:
  push:
    branches:
      - deploy 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Check out the repository
      uses: actions/checkout@v3

    # Step 2: Set up .NET 8 SDK
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    # Step 3: Build Docker image
    - name: Build Docker image
      run: docker build -t capstone-api:latest .

    # Step 4: Log in to Docker Hub (nếu bạn dùng Docker Hub)
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 5: Push Docker image to Docker Hub
    - name: Push Docker image
      run: docker tag capstone-api:latest ${{ secrets.DOCKER_USERNAME }}/capstone-api:latest && docker push ${{ secrets.DOCKER_USERNAME }}/capstone-api:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    # Step 1: Check out the code
    - name: Check out the repository
      uses: actions/checkout@v3

    # Step 2: Deploy to EC2 via SSH
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        passphrase: ${{ secrets.EC2_PASSPHRASE }}
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/capstone-api:latest
          docker-compose down
          docker-compose up -d
