name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t capstone-api .

      - name: Run Docker Container
        run: |
          docker run -d -p 80:80 --name capstone-api capstone-api
